## One vs All Logistic

In [528]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
from sklearn.preprocessing import StandardScaler

In [529]:
df = pd.read_csv('wine-quality/data.csv',delimiter=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            9.2              0.25         0.34            1.20      0.026   
1            6.6              0.20         0.27           10.90      0.038   
2            5.7              0.22         0.22           16.65      0.044   
3            7.2              0.23         0.39           14.20      0.058   
4            7.6              0.35         0.47           13.30      0.037   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 31.0                  93.0  0.99160  2.93       0.37   
1                 29.0                 130.0  0.99496  3.11       0.44   
2                 39.0                 110.0  0.99855  3.24       0.48   
3                 49.0                 192.0  0.99790  2.98       0.48   
4                 42.0                 116.0  0.99822  3.04       0.50   

   alcohol  quality  
0     11.3        7  
1     10.5        7  
2      9.0        6  
3      9.0        7  
4      9.2        5

In [530]:
lrr=0.01
itr=1000
X = df.drop(['quality'],axis=1)
Y = df['quality']

In [531]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)
# Y_train = df['quality']
# Y_train
A=X_train
B=X_test
C=Y_train
D=Y_test
def sklearn():
    lr = LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=itr)
    lr.fit(A, C) 
    y_pred = lr.predict(B)
    score = lr.score(B,D)
    print("Score: ",score)
    print((D == y_pred).mean())
    print(confusion_matrix(D,y_pred))
    print(classification_report(D,y_pred))
    print("Accuracy using SK learn: ",accuracy_score(D, y_pred)*100)

In [532]:
X_train = pd.concat([X_train,Y_train],axis=1)
ones = np.ones([X_train.shape[0],1])
Y_train = X_train.iloc[:,11:12].values
X_train = X_train.iloc[:,0:11]
X_train = np.concatenate((ones,X_train),axis=1)
X_train

array([[ 1.  ,  6.7 ,  0.34, ...,  3.  ,  0.47, 12.2 ],
       [ 1.  ,  7.5 ,  0.15, ...,  3.24,  0.44, 10.  ],
       [ 1.  ,  8.  ,  0.33, ...,  3.12,  0.36, 11.6 ],
       ...,
       [ 1.  ,  6.7 ,  0.34, ...,  3.19,  0.49,  9.3 ],
       [ 1.  ,  6.8 ,  0.19, ...,  3.12,  0.48,  9.6 ],
       [ 1.  ,  7.  ,  0.15, ...,  2.96,  0.39,  9.  ]])

In [533]:
theta = np.zeros([15,12])
theta.shape

(15, 12)

In [534]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def grad_des(X_train,Y_train,thh,lrr,itr): 
    for i in range(itr):
        h = sigmoid(np.dot(X_train,thh.T))
        thh = thh - (lrr/len(X_train)) * np.sum(X_train * (h - Y_train), axis=0)  
    return thh

In [535]:
for i in range(0,11):
    tt = np.zeros([1,12])
    W = np.array(Y_train)
    for j in range(len(W)):
        if W[j] == i:
            W[j] = 1
        else:
            W[j] = 0
    theta[i]=grad_des(X_train,W,tt,lrr,itr)
#     print(X_train.shape)

In [536]:
y_pred = []
for index,rows in X_test.iterrows():
    rows = list(rows)
    m=0
    for a in range(0,11):
        y = 0
        for i in range(len(rows)):
            y = y + rows[i]*theta[a][i+1]
        y = y + theta[a][0]
        y = sigmoid(y)
        if y >= m:
            label = a
            m = y
    y_pred.append(label)
# y_pred

In [539]:
# print((y_pred == Y_test).mean()*100)
print(confusion_matrix(Y_test,y_pred))
# print(classification_report(Y_test,y_pred))
print("Accuracy: ", accuracy_score(Y_test, y_pred)*100)

[[  0   0   0   7   0   0   0]
 [  0   2   4  19   0   0   0]
 [  0   4  19 222   0   0   0]
 [  0   2  12 386   0   0   0]
 [  0   0   3 168   0   0   0]
 [  0   0   0  33   0   0   0]
 [  0   0   0   1   0   0   0]]
Accuracy:  46.14512471655329


In [538]:
sklearn()

Score:  0.518140589569161
0.518140589569161
[[  0   0   2   5   0   0   0]
 [  0   0  15   8   2   0   0]
 [  0   0 114 129   2   0   0]
 [  0   0  72 306  22   0   0]
 [  0   0  10 124  37   0   0]
 [  0   0   2  17  14   0   0]
 [  0   0   0   1   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         7
           4       0.00      0.00      0.00        25
           5       0.53      0.47      0.50       245
           6       0.52      0.77      0.62       400
           7       0.48      0.22      0.30       171
           8       0.00      0.00      0.00        33
           9       0.00      0.00      0.00         1

   micro avg       0.52      0.52      0.52       882
   macro avg       0.22      0.21      0.20       882
weighted avg       0.48      0.52      0.48       882

Accuracy using SK learn:  51.8140589569161


/home/keshu/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/home/keshu/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
